- name: Install nginx package
  dnf:
    name: "{{ nginx_package }}"
    state: present
    update_cache: yes

- name: Create web root directory
  file:
    path: "{{ nginx_root_dir }}"
    state: directory
    mode: '0755'

- name: Deploy nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    mode: '0644'
  notify: restart nginx

- name: Ensure nginx is started and enabled
  service:
    name: "{{ nginx_service }}"
    state: started
    enabled: yes
